# Generated by Django 5.0.6 on 2024-05-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iha_rent', '0004_alter_users_email_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='ihadetails',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rentrecords',
            name='iha_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentrecords',
            name='user_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
