# Generated by Django 5.0.6 on 2024-05-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iha_rent', '0005_ihadetails_height_rentrecords_iha_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentrecords',
            old_name='stard_date',
            new_name='start_date',
        ),
    ]
