# Generated by Django 5.0.6 on 2024-05-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iha_rent', '0006_rename_stard_date_rentrecords_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentrecords',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rentrecords',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
