version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: baykar_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3729

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: baykar_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3729
      DATABASE_URL: postgres://postgres:3729@db:5432/baykar_project

volumes:
  postgres_data:

